### ISSUE TITLE
[#2] [FEAT]: Search Bar Funcionality

### ISSUE THREAD

**Issue by biancacangussu** [biancacangussu/potterpedia#2]
**Description:**
Implement a search bar that filters cards on all site pages except the Home page.

**Tasks:**
- [ ]  Add search functionality on Characters, Potions, and Spells pages.
- [ ] Ensure the search updates cards according to user input.
- [ ] Test the functionality to ensure filters are working correctly.
