### ISSUE TITLE
[#3] [FEAT]: Remove Search Bar on Home Page

### ISSUE THREAD

**Issue by biancacangussu** [biancacangussu/potterpedia#3]
**Description:**
Disable or remove the search bar on the Home page.

**Tasks:**
- [ ] Identify the search component on the Home page.
- [ ] Disable or remove the search component on the Home page.
- [ ] Test to ensure the search bar does not appear on the Home page.
