### ISSUE TITLE
[#4] [FEAT]: Favorite Bar

### ISSUE THREAD

**Issue by biancacangussu** [biancacangussu/potterpedia#4]
**Description:**
Add a feature that allows users to mark cards as favorites.

**Tasks:**
- [ ] Design the user interface for marking favorites.
- [ ] Implement the logic for storing favorites.
- [ ] Add a favorites button or icon on the cards.
- [ ] Test the functionality to favorite and unfavorite cards.
