### ISSUE TITLE
[#5] [FEAT]: Render only Cards with Characteristics Chips

### ISSUE THREAD

**Issue by biancacangussu** [biancacangussu/potterpedia#5]
**Description:**
Modify the pages to display only cards that have characteristics.

**Tasks:**
- [ ] Define which characteristics are essential for display.
- [ ] Create the logic to only display the right cards.
- [ ] Test the card rendering to ensure the correct information is displayed.
