### ISSUE TITLE
[#6] [FEAT]: Design the Homepage

### ISSUE THREAD

**Issue by biancacangussu** [biancacangussu/potterpedia#6]
**Description:**
Create and implement the design for the site's homepage.

**Tasks:**
- [ ]  Create a Figma for the homepage design.
- [ ] Implement styles and layout for the homepage.
- [ ] Test the homepage on different devices and browsers.
